set -eux

URL=https://www.sqlite.org/2022/sqlite-amalgamation-3380500.zip

rm -vrf sqlite-amalgamation-*
curl -o sqlite-amalgamation.zip "$URL"
unzip sqlite-amalgamation.zip

for f in sqlite3.c sqlite3.h
do
	if test "$f" = "sqlite3.h"
	then
		out="_$f"
	else
		out="$f"
	fi
	echo "/* Generated by fetch-sqlite3.sh */ " > "$out"
	echo "/* Wrapped in guard and renamed to allow bindings use system library */"
	echo "#ifdef USE_LIBSQLITE3" >> "$out"
	if test "$f" = "sqlite3.h"
	then
		echo "#include <sqlite3.h>" >> "$out"
	fi
	echo "#else" >> "$out"
	cat sqlite-amalgamation-*/"$f" >> "$out"
	echo "#endif" >> "$out"
done
